name: "Static Analysis"

concurrency:
  group: "sa-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  static-analysis-phpstan:
    name: "Static Analysis (PHPStan)"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.1"
          tools: "cs2pr"

      - name: "Install dependencies"
        uses: "ramsey/composer-install@v2"

      - name: "Run PHPStan"
        run: "./vendor/bin/phpstan --error-format=github"

  static-analysis-rector:
    name: "Static Analysis (Rector)"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.1"

      - name: "Install dependencies"
        uses: "ramsey/composer-install@v2"

      - name: "Run Rector"
        run: "./vendor/bin/rector --dry-run"
